### ISSUE TITLE
How to Run

### ISSUE THREAD

**Issue by kishoredr** [nsudhanva/node-js-kubernetes-helm#1]
Add me Readme.md file the procedures

**Comment by nsudhanva** [comment]
Added now. You can read the README.md file here: https://github.com/nsudhanva/node-js-kubernetes-helm/blob/master/README.md

**Comment by kishoredr** [comment]
Thank you @nsudhanva

**Comment by nsudhanva** [comment]
@kishoredr I have updated the repo again to work with Grafana, Prometheus, Jaegar, Zipkin and OpenTracing
